name = "new-ne222-playbeat-live"
main = "src/worker/index.ts"
compatibility_date = "2026-10-07"
workers_dev = true

[build]
command = "npm run build"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "CATALOG_DB"
database_name = "new-ne222-provider"
database_id = "c70f6682-200f-4bfc-837f-8caff766325e"

[[routes]]
pattern = "playbeat.live"
custom_domain = true

[[routes]]
pattern = "www.playbeat.live"
custom_domain = true

[triggers]
crons = ["*/15 * * * *"]
