name = "new-ne222"
main = "src/worker/index.ts"
compatibility_date = "2026-10-07"
workers_dev = true

[build]
command = "npm run build"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
STATIC_ONLY = "true"

[[routes]]
pattern = "playbeattv.buzz"
custom_domain = true
